# Use Node.js 21.1.0 as a parent image
FROM node:21.1.0

# Set the working directory to /app
WORKDIR /app

# Copy the frontend directory contents into the container at /app
COPY frontend /app/frontend

# Install dependencies and build the React app
WORKDIR /app/frontend
RUN apt-get update && apt-get install -y netcat-openbsd
RUN npm install
RUN npm run build

# Expose the React app port
EXPOSE 3000

# Run the React app
CMD ["npm", "start"]
