version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    networks:
      - my_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: >
      sh -c 'until nc -zv backend 5000; do echo "Waiting for backend to be ready..."; sleep 1; done && npm start'
    networks:
      - my_network

networks:
  my_network:
